// Auto-generated by tauri-specta. Do not edit.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getVersion: () => __TAURI_INVOKE<string>("get_version"),
	getInterfaces: () => typedError<InterfaceInfo[], string>(__TAURI_INVOKE("get_interfaces")),
	startCapture: (request: CaptureRequest) => typedError<CaptureResult, string>(__TAURI_INVOKE("start_capture", { request })),
	stopCapture: () => typedError<null, string>(__TAURI_INVOKE("stop_capture")),
	checkPrivileges: () => __TAURI_INVOKE<boolean>("check_privileges"),
	getPrivilegeStatus: () => __TAURI_INVOKE<PrivilegeStatus>("get_privilege_status"),
	installBpfHelper: () => typedError<null, string>(__TAURI_INVOKE("install_bpf_helper")),
};

/* Types */
export type CaptureRequest = {
	interfaceName: string,
	protocol: string,
};

export type CaptureResult = {
	switchName: string,
	switchIp: string,
	switchPort: string,
	nativeVlan: string,
	voiceVlan: string,
	mtu: string,
	switchModel: string,
};

export type InterfaceInfo = {
	name: string,
	description: string,
	addresses: string,
	hasIp: boolean,
};

export type PrivilegeStatus = {
	hasAccess: boolean,
	helperInstalled: boolean,
	inBpfGroup: boolean,
	canInstall: boolean,
	platform: string,
	npcapInstalled: boolean,
	npcapNonAdmin: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

