mod capture;
pub mod cli;
mod privilege;

use serde::{Deserialize, Serialize};
use specta::Type;
use tokio::sync::Mutex;
use tokio_util::sync::CancellationToken;

#[derive(Serialize, Clone, Type)]
#[serde(rename_all = "camelCase")]
pub struct InterfaceInfo {
    pub name: String,
    pub description: String,
    pub addresses: String,
    pub has_ip: bool,
}

#[derive(Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct CaptureRequest {
    pub interface_name: String,
    pub protocol: String,
}

#[derive(Serialize, Clone, Type)]
#[serde(rename_all = "camelCase")]
pub struct CaptureResult {
    pub switch_name: String,
    pub switch_ip: String,
    pub switch_port: String,
    pub native_vlan: String,
    pub voice_vlan: String,
    pub mtu: String,
    pub switch_model: String,
}

/// Holds the cancellation token for the currently running capture (if any).
/// `start_capture` cancels the previous token and replaces it; `stop_capture`
/// cancels whatever's there.
#[derive(Default)]
struct CaptureState(Mutex<Option<CancellationToken>>);

#[tauri::command]
#[specta::specta]
fn get_version() -> String {
    env!("CARGO_PKG_VERSION").to_string()
}

#[tauri::command]
#[specta::specta]
fn get_interfaces() -> Result<Vec<InterfaceInfo>, String> {
    capture::list_interfaces()
}

#[tauri::command]
#[specta::specta]
async fn start_capture(
    request: CaptureRequest,
    state: tauri::State<'_, CaptureState>,
) -> Result<CaptureResult, String> {
    let cancel = CancellationToken::new();
    {
        let mut current = state.0.lock().await;
        if let Some(prev) = current.take() {
            prev.cancel();
        }
        *current = Some(cancel.clone());
    }

    let result = capture::run(request, cancel.clone()).await;

    // Clear the slot if it's still our token.
    let mut current = state.0.lock().await;
    if let Some(ref tok) = *current {
        if tok.is_cancelled() || std::ptr::eq(tok as *const _, &cancel as *const _) {
            *current = None;
        }
    }
    result
}

#[tauri::command]
#[specta::specta]
async fn stop_capture(state: tauri::State<'_, CaptureState>) -> Result<(), String> {
    let mut current = state.0.lock().await;
    if let Some(tok) = current.take() {
        tok.cancel();
    }
    Ok(())
}

#[tauri::command]
#[specta::specta]
fn check_privileges() -> bool {
    privilege::has_capture_privilege()
}

#[tauri::command]
#[specta::specta]
fn get_privilege_status() -> privilege::PrivilegeStatus {
    privilege::get_privilege_status()
}

#[tauri::command]
#[specta::specta]
fn install_bpf_helper() -> Result<(), String> {
    privilege::install_bpf_helper()
}

/// Build the tauri-specta `Builder` that registers every command and
/// (via the `Type` derive on each request/response struct) every type
/// the frontend can see across the IPC boundary. Single source of
/// truth for both the runtime invoke handler and the generated
/// `frontend/src/bindings.ts`.
fn make_specta_builder() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new().commands(tauri_specta::collect_commands![
        get_version,
        get_interfaces,
        start_capture,
        stop_capture,
        check_privileges,
        get_privilege_status,
        install_bpf_helper,
    ])
}

/// Regenerate `frontend/src/bindings.ts` from the current set of
/// commands and types. Called from `run()` in debug builds so dev
/// launches keep the file fresh, and from a unit test so `cargo test`
/// regenerates it during CI — at which point a `git diff --exit-code`
/// step catches anyone who changed a command signature without
/// committing the matching TS update.
fn export_bindings() -> Result<(), Box<dyn std::error::Error>> {
    make_specta_builder().export(
        specta_typescript::Typescript::default()
            .header("// Auto-generated by tauri-specta. Do not edit.\n"),
        "../frontend/src/bindings.ts",
    )?;
    Ok(())
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let specta_builder = make_specta_builder();

    #[cfg(debug_assertions)]
    export_bindings().expect("failed to export typescript bindings");

    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_os::init())
        .manage(CaptureState::default())
        .invoke_handler(specta_builder.invoke_handler())
        .setup(move |app| {
            // macOS: apply NSVisualEffectView vibrancy to the window so
            // the Tahoe / Liquid Glass material shows through any
            // transparent regions in the WebView.
            #[cfg(target_os = "macos")]
            {
                use tauri::Manager;
                use window_vibrancy::{
                    apply_vibrancy, NSVisualEffectMaterial, NSVisualEffectState,
                };
                if let Some(window) = app.get_webview_window("main") {
                    let _ = apply_vibrancy(
                        &window,
                        NSVisualEffectMaterial::HudWindow,
                        Some(NSVisualEffectState::Active),
                        None,
                    );
                }
            }
            let _ = app;
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

#[cfg(test)]
mod specta_tests {
    use super::export_bindings;

    /// Regenerates `frontend/src/bindings.ts` whenever `cargo test` runs.
    /// Local dev: nothing to do — the file just stays current. CI: the
    /// `git diff --exit-code frontend/src/bindings.ts` step right after
    /// `cargo test` fails the run if a command signature or data struct
    /// changed without committing the regenerated TS.
    #[test]
    fn typescript_bindings_regenerate() {
        export_bindings().expect("failed to export typescript bindings");
    }
}
