// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH A MODIWL
// This file is automatically generated. DO NOT EDIT

export interface InterfaceInfo {
    name: string;
    description: string;
    addresses: string;
}

export interface CaptureRequest {
    interfaceName: string;
    protocol: string;
}

export interface CaptureResult {
    switchName: string;
    switchIP: string;
    switchPort: string;
    nativeVLAN: string;
    voiceVLAN: string;
    switchModel: string;
}

export function CheckPrivileges(): Promise<boolean>;

export function GetInterfaces(): Promise<Array<InterfaceInfo>>;

export function GetVersion(): Promise<string>;

export function StartCapture(arg1: CaptureRequest): Promise<CaptureResult>;

export function StopCapture(): Promise<void>;
