// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH A MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPrivileges() {
    return window['go']['main']['App']['CheckPrivileges']();
}

export function GetInterfaces() {
    return window['go']['main']['App']['GetInterfaces']();
}

export function GetVersion() {
    return window['go']['main']['App']['GetVersion']();
}

export function StartCapture(arg1) {
    return window['go']['main']['App']['StartCapture'](arg1);
}

export function StopCapture() {
    return window['go']['main']['App']['StopCapture']();
}
