// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {capture} from '../models';
import {privilege} from '../models';

export function CheckPrivileges():Promise<boolean>;

export function GetInterfaces():Promise<Array<capture.InterfaceInfo>>;

export function GetPrivilegeStatus():Promise<privilege.PrivilegeStatus>;

export function GetVersion():Promise<string>;

export function InstallBPFHelper():Promise<void>;

export function StartCapture(arg1:capture.CaptureRequest):Promise<capture.CaptureResult>;

export function StopCapture():Promise<void>;
